apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-dep
  template:
    metadata:
      labels:
        app: backend-dep
    spec:
      containers:
      - name: backend
        image: papiyamazumder/backend-repo:01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password@mongo:27017/user-account?authSource=admin"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-dep
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
